// Generated by native/generate_catalog.py; edit native/catalog.json.
#pragma once
#include "game_ids.hpp"
#include <stdexcept>
namespace rebirths {
enum class FeatureId {
    FastTextureConversion,
    FastFaceTextureCreation,
    AdvFastForward,
    AdvAutoSkip,
    SkipTutorials,
    BattleLoadDelaySkip,
    SkipChapterIntros,
    DungeonMovementFix,
    UncompressedAssets,
    NepstationSkip,
    TrimSilentAudioTails,
};
enum class PreparerPolicy { Managed, Preserve };
struct FeatureSpec {
    FeatureId id; const wchar_t* key; uint32_t gameMask;
    int runtimeDefault, freshDefault, existingDefault;
    PreparerPolicy preparerPolicy; const wchar_t* uiLabel;
};
inline constexpr std::array<FeatureSpec, 11> Features = {{
    {FeatureId::FastTextureConversion, L"FastTextureConversion", 15, 1, 1, 1, PreparerPolicy::Managed, L"Fast texture conversion"},
    {FeatureId::FastFaceTextureCreation, L"FastFaceTextureCreation", 12, 0, 0, 0, PreparerPolicy::Preserve, nullptr},
    {FeatureId::AdvFastForward, L"AdvFastForward", 15, 0, 0, 0, PreparerPolicy::Managed, L"Story fast-forward (ADV)"},
    {FeatureId::AdvAutoSkip, L"AdvAutoSkip", 15, 0, 0, 0, PreparerPolicy::Managed, L"Auto-skip story (ADV)"},
    {FeatureId::SkipTutorials, L"SkipTutorials", 15, 1, 1, 1, PreparerPolicy::Managed, L"Skip tutorials"},
    {FeatureId::BattleLoadDelaySkip, L"BattleLoadDelaySkip", 4, 0, 0, 0, PreparerPolicy::Managed, L"Skip battle loading delay"},
    {FeatureId::SkipChapterIntros, L"SkipChapterIntros", 2, 0, 0, 0, PreparerPolicy::Managed, L"Skip chapter intros"},
    {FeatureId::DungeonMovementFix, L"DungeonMovementFix", 8, 1, 1, 1, PreparerPolicy::Managed, L"Fix dungeon movement"},
    {FeatureId::UncompressedAssets, L"UncompressedAssets", 15, 0, 1, 0, PreparerPolicy::Managed, L"Use prepared assets"},
    {FeatureId::NepstationSkip, L"NepstationSkip", 4, 0, 0, 0, PreparerPolicy::Managed, L"Skip Nepstation"},
    {FeatureId::TrimSilentAudioTails, L"TrimSilentAudioTails", 7, 1, 1, 1, PreparerPolicy::Preserve, nullptr},
}};
constexpr const FeatureSpec& FeatureSpecFor(FeatureId id) {
    for (const auto& feature : Features) if (feature.id == id) return feature;
    throw std::invalid_argument("Unsupported feature ID");
}
constexpr bool Supports(const FeatureSpec& feature, GameId game) noexcept {
    return ValidGameId(game) && (feature.gameMask & (uint32_t{1} << static_cast<uint32_t>(game))) != 0;
}
constexpr bool Supports(FeatureId feature, GameId game) { return Supports(FeatureSpecFor(feature), game); }
template<class Read> bool ReadRuntimeFeature(GameId game, FeatureId id, Read read) {
    const auto& feature = FeatureSpecFor(id);
    return Supports(feature, game) && read(feature.key, feature.runtimeDefault) != 0;
}
}
