// Generated by native/generate_catalog.py; edit native/catalog.json.
#pragma once
#include <array>
#include <cstdint>
namespace rebirths {
enum class GameId : uint32_t {
    Rebirth1 = 0,
    Rebirth2 = 1,
    Rebirth3 = 2,
    SegaHardGirls = 3,
};
inline constexpr std::array<GameId, 4> AllGameIds = {GameId::Rebirth1, GameId::Rebirth2, GameId::Rebirth3, GameId::SegaHardGirls};
constexpr bool ValidGameId(GameId id) noexcept {
    for (auto valid : AllGameIds) if (id == valid) return true;
    return false;
}
}
