# Generated by native/generate_catalog.py; edit native/catalog.json.
@{
    Targets = @{
        'rebirth1' = @{ Id = 0; Executable = 'NeptuniaReBirth1.exe'; Process = 'NeptuniaReBirth1'; Hashes = @('0A6FDAE55681019C9612F2DA5E59C7539A2DEF22F66546695B8E9978CA88AB71', '40D3439CBE97A4411DFB64BEB04C5F65E06BE1969FC9639AFA7EC012918C2D53'); Record = 'reports/rebirth1-local-install.json' }
        'rebirth2' = @{ Id = 1; Executable = 'NeptuniaReBirth2.exe'; Process = 'NeptuniaReBirth2'; Hashes = @('F0B0B9FE40A26A001D0AC87702D51844F19900CFABE3D38680B885CC607C2FB2', '987FDCF2840E8BBF94CE706746BCD3168B8B94E4984824262EBB7DFE69B3A156'); Record = 'reports/rebirth2-local-install.json' }
        'rebirth3' = @{ Id = 2; Executable = 'NeptuniaReBirth3.exe'; Process = 'NeptuniaReBirth3'; Hashes = @('455AB306A0E44B6E97AF1CE2F7C6CF3B56C0352AAA1D62D24FFFC2B11088751B', '41F988B3BCBEB6C5953B995CED27EDB2F8FBC7D9C168203AD65C7C9213ECDD3D'); Record = 'reports/rebirth3-local-install.json' }
        'neptune-vs-sega-hard-girls' = @{ Id = 3; Executable = 'Neptune VSSega Hard Girls.exe'; Process = 'Neptune VSSega Hard Girls'; Hashes = @('AF9550B0B5AB90810E31274066F13B3E1B224EF5960951A44D2ACD53903523E5', 'A3C1AAB3713B569630361B5FAE951DA6987E38651AC1C378F3B6D5DC3D8F1A1B'); Record = 'reports/sega-hard-girls-local-install.json' }
    }
    ShippedDefaults = @{
        'FastTextureConversion' = '1'
        'FastFaceTextureCreation' = '0'
        'AdvFastForward' = '0'
        'AdvAutoSkip' = '0'
        'SkipTutorials' = '1'
        'BattleLoadDelaySkip' = '0'
        'SkipChapterIntros' = '0'
        'DungeonMovementFix' = '1'
        'UncompressedAssets' = '0'
        'NepstationSkip' = '0'
        'TrimSilentAudioTails' = '1'
    }
}
