"""Generate checked-in metadata; --check rejects stale outputs without writing.

The catalog is the production authority. Independent tests keep their own
baseline/default expectations, rather than generating their oracles here.
"""
import argparse
import json
import pprint
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent
HEADER = "// Generated by native/generate_catalog.py; edit native/catalog.json.\n"


def need(condition, message):
    if not condition:
        raise ValueError(message)


def validate(data):
    need(isinstance(data, dict) and set(data) == {"version", "targets", "features"} and
         type(data["version"]) is int and data["version"] == 1,
         "unsupported catalog schema")
    targets, features = data["targets"], data["features"]
    need(isinstance(targets, list) and isinstance(features, list), "catalog rows must be lists")
    need(len(targets) == 4 and 0 < len(features) <= 64, "unexpected catalog cardinality")
    # These IDs are an on-disk format contract, not positions in a list.
    stable_ids = {"Rebirth1": 0, "Rebirth2": 1, "Rebirth3": 2, "SegaHardGirls": 3}
    seen_names, seen_hashes = set(), set()
    target_keys = {"id", "enum", "name", "executable", "steam_folder", "local_record",
                   "hashes", "image_base", "text_start", "text_end"}
    for t in targets:
        need(isinstance(t, dict) and set(t) == target_keys, "unexpected target fields")
        need(type(t["id"]) is int and stable_ids.get(t["enum"]) == t["id"], "changed serialized game ID")
        need(t["name"] not in seen_names and re.fullmatch(r"[a-z0-9-]+", t["name"]), "duplicate/invalid target name")
        seen_names.add(t["name"])
        need(t["executable"].endswith(".exe") and not any(c in t["executable"] for c in "/\\'\""), "invalid executable")
        need(t["steam_folder"] not in ("", ".", "..") and
             not any(c in t["steam_folder"] for c in '/\\\n\r\0'), "invalid Steam folder")
        need(set(t["hashes"]) == {"baseline", "laa", "ntcore"}, "unexpected identity variants")
        for h in t["hashes"].values():
            need(re.fullmatch(r"[0-9a-f]{64}", h) and h not in seen_hashes, "duplicate/invalid digest")
            seen_hashes.add(h)
        need(all(type(t[k]) is int for k in ("image_base", "text_start", "text_end")) and
             0 < t["text_start"] < t["text_end"] < 2**32 and 0 < t["image_base"] < 2**32, "invalid image bounds")
        need(re.fullmatch(r"build/[a-z0-9-]+\.json", t["local_record"]), "invalid local record")
    need({t["enum"] for t in targets} == set(stable_ids), "duplicate/missing game")
    feature_keys = {"key", "member", "support", "runtime_default", "fresh_default", "existing_default",
                    "preparer_policy", "ui_label", "comment"}
    names, members = set(), set()
    for f in features:
        need(isinstance(f, dict) and set(f) == feature_keys, "unexpected feature fields")
        need(re.fullmatch(r"[A-Z][A-Za-z0-9]+", f["key"]) and f["key"] not in names, "duplicate/invalid feature")
        names.add(f["key"])
        need(f["support"] and len(set(f["support"])) == len(f["support"]) and
             set(f["support"]) <= set(stable_ids), "invalid feature support")
        need(all(type(f[k]) is int and f[k] in (0, 1) for k in
                 ("runtime_default", "fresh_default", "existing_default")), "invalid feature defaults")
        need(f["preparer_policy"] in ("managed", "preserve"), "invalid preparer policy")
        need("\n" not in f["comment"], "multiline INI comment")
        if f["preparer_policy"] == "managed":
            need(isinstance(f["member"], str) and re.fullmatch(r"[a-z][A-Za-z0-9]+", f["member"]) and
                 f["member"] not in members and f["ui_label"], "invalid managed feature")
            members.add(f["member"])
        else:
            need(f["member"] is None and f["ui_label"] is None, "preserved feature has a UI binding")
    return sorted(targets, key=lambda t: t["id"]), features


def quoted(value):
    return json.dumps(value, ensure_ascii=True)


def digest(h):
    return "{" + ",".join("0x" + h[i:i+2] for i in range(0, 64, 2)) + "}"


def outputs(data):
    targets, features = validate(data)
    ids = HEADER + "#pragma once\n#include <array>\n#include <cstdint>\nnamespace rebirths {\n"
    ids += "enum class GameId : uint32_t {\n"
    ids += "".join(f"    {t['enum']} = {t['id']},\n" for t in targets) + "};\n"
    ids += "inline constexpr std::array<GameId, 4> AllGameIds = {" + ", ".join("GameId::"+t["enum"] for t in targets) + "};\n"
    ids += "constexpr bool ValidGameId(GameId id) noexcept {\n    for (auto valid : AllGameIds) if (id == valid) return true;\n    return false;\n}\n}\n"
    target = HEADER + '#pragma once\n#include "rebirths_patch.hpp"\nnamespace rebirths::catalog {\n'
    target += "struct Target { GameSpec spec; const char* name; const wchar_t* steamFolder; };\n"
    target += "inline constexpr std::array<Target, 4> Targets = {{\n"
    for t in targets:
        target += "    {{GameId::"+t["enum"]+", L"+quoted(t["executable"])+",\n"
        target += "        " + ",\n        ".join(digest(t["hashes"][h]) for h in ("baseline", "laa", "ntcore")) + ",\n"
        target += "        " + ", ".join(f"0x{t[k]:08x}" for k in ("image_base", "text_start", "text_end")) + "},\n"
        target += "        " + quoted(t["name"]) + ", L" + quoted(t["steam_folder"]) + "},\n"
    target += "}};\n}\n"
    feature = HEADER + '#pragma once\n#include "game_ids.hpp"\n#include <stdexcept>\nnamespace rebirths {\n'
    feature += "enum class FeatureId {\n" + "".join("    "+f["key"]+",\n" for f in features) + "};\n"
    feature += "enum class PreparerPolicy { Managed, Preserve };\n"
    feature += "struct FeatureSpec {\n    FeatureId id; const wchar_t* key; uint32_t gameMask;\n    int runtimeDefault, freshDefault, existingDefault;\n    PreparerPolicy preparerPolicy; const wchar_t* uiLabel;\n};\n"
    feature += f"inline constexpr std::array<FeatureSpec, {len(features)}> Features = {{{{\n"
    for f in features:
        mask = sum(1 << next(t["id"] for t in targets if t["enum"] == name) for name in f["support"])
        label = "L"+quoted(f["ui_label"]) if f["ui_label"] is not None else "nullptr"
        feature += f"    {{FeatureId::{f['key']}, L{quoted(f['key'])}, {mask}, {f['runtime_default']}, {f['fresh_default']}, {f['existing_default']}, PreparerPolicy::{f['preparer_policy'].title()}, {label}}},\n"
    feature += "}};\nconstexpr const FeatureSpec& FeatureSpecFor(FeatureId id) {\n    for (const auto& feature : Features) if (feature.id == id) return feature;\n    throw std::invalid_argument(\"Unsupported feature ID\");\n}\n"
    feature += "constexpr bool Supports(const FeatureSpec& feature, GameId game) noexcept {\n    return ValidGameId(game) && (feature.gameMask & (uint32_t{1} << static_cast<uint32_t>(game))) != 0;\n}\n"
    feature += "constexpr bool Supports(FeatureId feature, GameId game) { return Supports(FeatureSpecFor(feature), game); }\n"
    feature += "template<class Read> bool ReadRuntimeFeature(GameId game, FeatureId id, Read read) {\n    const auto& feature = FeatureSpecFor(id);\n    return Supports(feature, game) && read(feature.key, feature.runtimeDefault) != 0;\n}\n}\n"
    managed = [f for f in features if f["member"]]
    fields = HEADER + "".join(f"    bool {f['member']} = FeatureSpecFor(FeatureId::{f['key']}).freshDefault != 0;\n" for f in managed)
    bindings = HEADER + "".join(f"    {{FeatureId::{f['key']}, &Settings::{f['member']}}},\n" for f in managed)
    py = '# Generated by native/generate_catalog.py; edit native/catalog.json.\n'
    py += "TARGET_CATALOG = " + pprint.pformat(targets, width=100, sort_dicts=False) + "\n"
    py += "FEATURE_CATALOG = " + pprint.pformat(features, width=100, sort_dicts=False) + "\n"
    py += "TARGETS = [(t['name'], t['executable'], t['hashes']['baseline']) for t in TARGET_CATALOG]\n"
    py += "def target_for_id(game):\n    for target in TARGET_CATALOG:\n        if type(game) is int and target['id'] == game:\n            return target\n    raise ValueError('Unsupported game ID')\n"
    ps = "# Generated by native/generate_catalog.py; edit native/catalog.json.\n@{\n    Targets = @{\n"
    for t in targets:
        ps += f"        '{t['name']}' = @{{ Id = {t['id']}; Executable = '{t['executable']}'; Process = '{t['executable'][:-4]}'; Hashes = @('{t['hashes']['baseline'].upper()}', '{t['hashes']['laa'].upper()}'); Record = '{t['local_record']}' }}\n"
    ps += "    }\n    ShippedDefaults = @{\n" + "".join(f"        '{f['key']}' = '{f['runtime_default']}'\n" for f in features) + "    }\n}\n"
    ini = "; Generated by native/generate_catalog.py; edit native/catalog.json.\n[Patches]\n"
    ini += "".join(f"; {f['comment']}\n{f['key']}={f['runtime_default']}\n" for f in features)
    ini += "\n[UncompressedAssets]\n; Relative paths start at the folder containing the game EXE, including Re;Birth3.\nDirectory=rebirths-speedrun-patch\\assets\n; Check every opened prepared asset for changes. Leave off when measuring performance.\nVerify=0\n"
    doc = "<!-- Generated by native/generate_catalog.py; edit native/catalog.json. -->\n"
    doc += "# Settings reference\n\nGenerated from `native/catalog.json`. `1` means on; `0` means off.\nThe shipped defaults apply when using the DLL directly; new installs use the preparer defaults.\n\n| INI setting | Supported games | Shipped default | New install | Existing INI without this setting | On update |\n| --- | --- | --- | --- | --- | --- |\n"
    for f in features:
        support = ", ".join(f["support"])
        policy = "Keep the saved value; edit in INI" if f["preparer_policy"] == "preserve" else "Load and save your choice on supported games"
        doc += f"| `{f['key']}` | {support} | {f['runtime_default']} | {f['fresh_default']} | {f['existing_default']} | {policy} |\n"
    return {"include/game_ids.hpp": ids, "include/target_catalog.hpp": target,
            "include/feature_catalog.hpp": feature, "include/prepare_feature_fields.inc": fields,
            "include/prepare_feature_bindings.inc": bindings, "catalog_data.py": py,
            "catalog-data.psd1": ps, "rebirths-patches.ini": ini, "CATALOG-REFERENCE.md": doc}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = outputs(json.loads((ROOT / "catalog.json").read_text(encoding="utf-8")))
    stale = []
    for relative, content in result.items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(relative)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("Stale catalog outputs: " + ", ".join(stale), file=sys.stderr)
        return 1
    print(f"Catalog {'checked' if args.check else 'generated'}: {len(result)} outputs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
